export default {
    LOGIN_SUCCESSFULL: 'LOGIN_SUCCESSFULL',
    GET_USER_SUCCESSFULL : 'GET_USER_SUCCESSFULL',
    GET_USERS_SUCCESSFULL : 'GET_USERS_SUCCESSFULL',
    ADD_USER_SUCCESSFULL : 'ADD_USER_SUCCESSFULL',
    SAVE_USER_SUCCESSFULL: 'SAVE_USER_SUCCESSFULL',    
    DELETE_USER_SUCCESSFULL: 'DELETE_USER_SUCCESSFULL',
    REFRESH_TOKEN_SUCCESSFULL: 'REFRESH_TOKEN_SUCCESSFULL',

    LOGIN_FAILED: 'LOGIN_FAILED',
    GET_USER_FAILED : 'GET_USER_FAILED',
    GET_USERS_FAILED : 'GET_USERS_FAILED',
    ADD_USER_FAILED : 'ADD_USER_FAILED',
    SAVE_USER_FAILED: 'SAVE_USER_FAILED',
    DELETE_USER_FAILED: 'DELETE_USER_FAILED',

    CANCEL_USER_SAVE: 'CANCEL_USER_SAVE',
    LOGOUT: 'LOGOUT',
}